insert into anime (id, title, link, image, score, members, genre, studios, source,
                   season, year, `rank`, popularity, scoring_count, episodes, air_status,
                   type, start_date, end_date, english_title, japanese_title, synopsis,
                   created_at, updated_at, large_image, rating, nsfw)
values (4765,
        'Attack on Titan',
        'https://example.com/anime/4765',
        'https://example.com/img/4765.jpg',
        9.12,
        2500000,
        'Action, Fantasy',
        'WIT Studio',
        'Manga',
        'SPRING',
        2013,
        2,
        1,
        1800000,
        25,
        'Finished Airing',
        'TV',
        '2013-04-07 00:00:00',
        '2013-09-29 00:00:00',
        'Attack on Titan',
        'Shingeki no Kyojin',
        'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans...',
        '2026-06-28 21:00:00',
        '2026-06-28 21:00:00',
        'https://example.com/img/4765_large.jpg',
        'R - 17+',
        'SFW');