name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Start MySQL and Configure Timezone
      run: |
        sudo systemctl start mysql
        echo "[mysqld]" | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf
        echo "default-time-zone = '+00:00'" | sudo tee -a /etc/mysql/mysql.conf.d/mysqld.cnf
        sudo systemctl restart mysql

    - name: Initialize MySQL Databases and Users
      run: |
        sudo mysql -v -uroot -proot --execute="DROP USER IF EXISTS 'uservices'@'localhost';"
        sudo mysql -v -uroot -proot --execute="CREATE USER 'uservices'@'localhost' IDENTIFIED BY 'uservices';"
        
        for database_name in 'allocations' 'backlog' 'registration' 'timesheets' 'anime'; do
          sudo mysql -v -uroot -proot --execute="DROP DATABASE IF EXISTS ${database_name}_test"
          sudo mysql -v -uroot -proot --execute="CREATE DATABASE ${database_name}_test"
          sudo mysql -v -uroot -proot --execute="GRANT ALL ON ${database_name}_test.* TO 'uservices'@'localhost';"
          sudo mysql -v -uroot -proot --execute="GRANT SELECT ON performance_schema.* TO 'uservices'@'localhost';"
        done
        
        sudo mysql -v -uuservices -puservices registration_test --execute="SELECT NOW();"

    - name: Setup Flyway and Run Migrations
      run: |
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.15.0/flyway-commandline-10.15.0-linux-x64.tar.gz | tar xvz
        export PATH=$PWD/flyway-10.15.0:$PATH
        
        flyway -cleanDisabled=false -user=uservices -password=uservices -url="jdbc:mysql://localhost:3306/allocations_test" -locations=filesystem:databases/allocations-database clean migrate
        flyway -cleanDisabled=false -user=uservices -password=uservices -url="jdbc:mysql://localhost:3306/backlog_test" -locations=filesystem:databases/backlog-database clean migrate
        flyway -cleanDisabled=false -user=uservices -password=uservices -url="jdbc:mysql://localhost:3306/registration_test" -locations=filesystem:databases/registration-database clean migrate
        flyway -cleanDisabled=false -user=uservices -password=uservices -url="jdbc:mysql://localhost:3306/timesheets_test" -locations=filesystem:databases/timesheets-database clean migrate
        flyway -cleanDisabled=false -user=uservices -password=uservices -url="jdbc:mysql://localhost:3306/anime_test" -locations=filesystem:databases/anime-database clean migrate

    - name: Build with Gradle Wrapper
      run: |
        chmod +x gradlew
        ./gradlew build
